// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUZk6wP2khccFg_xgm_kWpEBW2RwNvq1c',
    appId: '1:202823151597:web:62d60c893769b63d0681e4',
    messagingSenderId: '202823151597',
    projectId: 'self-care-a3b89',
    authDomain: 'self-care-a3b89.firebaseapp.com',
    storageBucket: 'self-care-a3b89.firebasestorage.app',
    measurementId: 'G-8L7LFJYXHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU_z824b_M7JS3mi25-fmpzXGkI0PCXQk',
    appId: '1:202823151597:android:e1f7e6ab76e3a4010681e4',
    messagingSenderId: '202823151597',
    projectId: 'self-care-a3b89',
    storageBucket: 'self-care-a3b89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhDzgmAKkD12Dfz1k06RP1IbPXMMnKP0U',
    appId: '1:202823151597:ios:c8a27380c0be877c0681e4',
    messagingSenderId: '202823151597',
    projectId: 'self-care-a3b89',
    storageBucket: 'self-care-a3b89.firebasestorage.app',
    iosBundleId: 'com.example.selfcareMobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhDzgmAKkD12Dfz1k06RP1IbPXMMnKP0U',
    appId: '1:202823151597:ios:c8a27380c0be877c0681e4',
    messagingSenderId: '202823151597',
    projectId: 'self-care-a3b89',
    storageBucket: 'self-care-a3b89.firebasestorage.app',
    iosBundleId: 'com.example.selfcareMobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUZk6wP2khccFg_xgm_kWpEBW2RwNvq1c',
    appId: '1:202823151597:web:d42e463a5f5485920681e4',
    messagingSenderId: '202823151597',
    projectId: 'self-care-a3b89',
    authDomain: 'self-care-a3b89.firebaseapp.com',
    storageBucket: 'self-care-a3b89.firebasestorage.app',
    measurementId: 'G-YB945EX2FG',
  );
}
